---
title: "Changepoint Analysis GHG"
output: html_document
date: "2023-02-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## GHG Changepoint 
```{r GHG  vs. Unemploymnet, echo=FALSE}
setwd("/Users/csuffaculty/Desktop/FHWA")

#read the dataset
dat<-read.csv("Data20221210.csv", header=TRUE)
library(ggplot2)
library(segmented)

GHG.dat<-dat[,colSums(is.na(dat))==0]
GHG.dat.sub<-GHG.dat[,c("year","TransportGHG","Unemployment.Rate.1","TransitPMT","TotLaneMiles","EVPrivateandPublicChargingStationLocations","populationTelework")]
GHG.dat.sub$GHG.1<-c(NA,GHG.dat.sub[1:19,"TransportGHG"])
plot.unemp<-ggplot(GHG.dat.sub, aes(x = Unemployment.Rate.1, y=TransportGHG))+geom_point() #plot raw data
lm.unemp<-lm(TransportGHG ~ Unemployment.Rate.1, data=GHG.dat.sub) #fit linear model
```
```{r changepoint analysis, echo=FALSE}
seg.unemp<-segmented(lm.unemp, seg.Z = ~ Unemployment.Rate.1)
summary(seg.unemp)
slope(seg.unemp)
confint(seg.unemp)
plot.segmented(seg.unemp, res=TRUE, col=2, xlab="Unemployment Rate", ylab="GHG", pch=16)
unemp.fitted<-fitted(seg.unemp)
unemp.model<-data.frame(Unemployment=GHG.dat.sub$Unemployment.Rate.1, GHG=unemp.fitted)
#plot.unemp+geom_line(data = unemp.model, aes(x = Unemployment, y = GHG), colour="red")
```


```{r GHG vs. TotLaneMiles, echo=FALSE}
plot.TotLaneMiles<-ggplot(GHG.dat.sub, aes(x = TotLaneMiles, y=TransportGHG))+geom_point() #plot raw data
lm.TotLaneMiles<-lm(TransportGHG ~ TotLaneMiles, data=GHG.dat.sub) #fit linear model
```

```{r changepoint analysis TotLaneMiles, echo=FALSE}
seg.TotLaneMiles<-segmented(lm.TotLaneMiles, seg.Z = ~ TotLaneMiles)
summary(seg.TotLaneMiles)
slope(seg.TotLaneMiles)
confint(seg.TotLaneMiles)
plot.segmented(seg.TotLaneMiles, res=TRUE, col=2, xlab="Total Lane Miles", ylab="GHG", pch=16)
TotLaneMiles.fitted<-fitted(seg.TotLaneMiles)
TotLaneMiles.model<-data.frame(Total.Lane.Miles=GHG.dat.sub$TotLaneMiles, GHG=TotLaneMiles.fitted)
#plot.TotLaneMiles+geom_line(data = TotLaneMiles.model, aes(x = Total.Lane.Miles, y = GHG), colour="red")
```


```{r GHG vs. TransitPMT, echo=FALSE}
plot.TransitPMT<-ggplot(GHG.dat.sub, aes(x = TransitPMT, y=TransportGHG))+geom_point() #plot raw data
lm.TransitPMT<-lm(TransportGHG ~ TransitPMT, data=GHG.dat.sub) #fit linear model
```

```{r changepoint analysis TransitPMT, echo=FALSE}
seg.TransitPMT<-segmented(lm.TransitPMT)
summary(seg.TransitPMT)
slope(seg.TransitPMT)
confint(seg.TransitPMT)
plot.segmented(seg.TransitPMT, res=TRUE, col=2, xlab="Transit PMT", ylab="GHG", pch=16)
TransitPMT.fitted<-fitted(seg.TransitPMT)
TransitPMT.model<-data.frame(TransitPMT=GHG.dat.sub$TransitPMT, GHG=TransitPMT.fitted)
#plot.TransitPMT+geom_line(data = TransitPMT.model, aes(x = TransitPMT, y = GHG), colour="red")
```



```{r GHG vs. EVPrivateandPublicChargingStationLocations, echo=FALSE}
plot.EVPrivateandPublicChargingStationLocations<-ggplot(GHG.dat.sub, aes(x = EVPrivateandPublicChargingStationLocations, y=TransportGHG))+geom_point() #plot raw data
lm.EVPrivateandPublicChargingStationLocations<-lm(TransportGHG ~ EVPrivateandPublicChargingStationLocations, data=GHG.dat.sub) #fit linear model
```

```{r changepoint analysis EVPrivateandPublicChargingStationLocations, echo=FALSE}
seg.EVPrivateandPublicChargingStationLocations<-segmented(lm.EVPrivateandPublicChargingStationLocations, seg.Z = ~ EVPrivateandPublicChargingStationLocations)
summary(seg.EVPrivateandPublicChargingStationLocations)
slope(seg.EVPrivateandPublicChargingStationLocations)
confint(seg.EVPrivateandPublicChargingStationLocations)
plot.segmented(seg.EVPrivateandPublicChargingStationLocations, res=TRUE, col=2, xlab="EV Private/Public Charging Station Locations", ylab="GHG", pch=16)
EVPrivateandPublicChargingStationLocations.fitted<-fitted(seg.EVPrivateandPublicChargingStationLocations)
EVPrivateandPublicChargingStationLocations.model<-data.frame(EVPrivateandPublicChargingStationLocations=GHG.dat.sub$EVPrivateandPublicChargingStationLocations, GHG=EVPrivateandPublicChargingStationLocations.fitted)
#plot.EVPrivateandPublicChargingStationLocations+geom_line(data = EVPrivateandPublicChargingStationLocations.model, aes(x = EVPrivateandPublicChargingStationLocations, y = GHG), colour="red")
```



```{r GHG vs. populationTelework, echo=FALSE}
plot.populationTelework<-ggplot(GHG.dat.sub, aes(x = populationTelework, y=TransportGHG))+geom_point() #plot raw data
lm.populationTelework<-lm(TransportGHG ~ populationTelework, data=GHG.dat.sub) #fit linear model
```

```{r changepoint analysis populationTelework, echo=FALSE}
seg.populationTelework<-segmented(lm.populationTelework)
summary(seg.populationTelework)
slope(seg.populationTelework)
confint(seg.populationTelework)
plot.segmented(seg.populationTelework, res=TRUE, col=2, xlab="Population Telework", ylab="GHG", pch=16)
populationTelework.fitted<-fitted(seg.populationTelework)
populationTelework.model<-data.frame(populationTelework=GHG.dat.sub$populationTelework, GHG=populationTelework.fitted)
#plot.populationTelework+geom_line(data = populationTelework.model, aes(x = populationTelework, y = GHG), colour="red")
```

